### ISSUE TITLE
rails new

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#1]
## TODO
Dockerを用いてrailsの環境構築をする

## 要件
- [x] `Dockerfile.dev` を作成し、Railsアプリを設定
- [x] `docker-compose.yml` にRails7.2と設定
- [x] `docker-compose up` でサービスを起動し、`rails new` を実行
- [x] DaisyUIのインストールとTailwind CSSの設定
- [x] GitHubにコードをpush

## ゴール
localhost:3000に入り、railsの初期画面が見れること
