### ISSUE TITLE
SpotifyAPIのセットアップ

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#109]
#### **TODO**
- [x] **Spotify Developer アカウントを作成**  
  - 必要な情報を入力してアカウントを作成する。
- [x] **Spotify Developer Dashboard で新しいアプリケーションを作成**  
  - アプリケーション名や説明を設定。
- [x] **クライアント ID とクライアントシークレットを取得**  
  - 作成したアプリケーションから情報を取得する。
- [x] **リダイレクト URL を設定**  
  - ローカル環境用にリダイレクトURLを設定（例: `http://localhost:3000/callback`）。  

#### **要件**
- [x] Spotify Developer アカウントが作成済みで、アプリケーションがDashboard上に登録されている。
- [x] クライアント ID とクライアントシークレットが正しく取得できている。
- [ ] リダイレクト URL が正しく設定されており、認証後にアプリケーションに戻れる。
