### ISSUE TITLE
SpotifyAPIをアプリと連携

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#110]
#### **TODO**
- [x] **`rspotify` と `dotenv-rails` をインストール**  
  - Gemfileに追加し、`bundle install` を実行する。
- [x] **環境変数にクライアント ID とクライアントシークレットを設定**  
  - `.env` ファイルを作成し、環境変数を設定する。
- [x] **Spotify API の認証設定を初期化コードに記述**  

#### **要件**
- [x] 必要なGemがインストールされている。
- [x] クライアント ID とクライアントシークレットが環境変数として正しく設定されている。
- [x] アプリケーションがSpotify APIと認証を通じて通信できる。
