### ISSUE TITLE
SpotifyAPIによる楽曲検索機能の実装

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#112]
#### **TODO**
- [ ] Spotify APIの検索エンドポイントを使用して楽曲データを取得。
  - 検索キーワードを送信し、楽曲名やアーティスト名に基づくデータを取得する。
  - 部分一致や大文字小文字を無視した検索が可能になるように設定。
- [ ] 取得したデータをモーダル内に表示。
  - 楽曲名、アーティスト名、ジャケット写真をリスト形式で表示。
  - プレビューURLがある場合のみ「プレビュー再生ボタン」を表示。
- [ ] 検索結果が空の場合は、「該当なし」のメッセージを表示。

#### **要件**
- [ ] Spotify APIが正しく動作し、以下のデータを取得・表示できる：
  - 楽曲名
  - アーティスト名
  - ジャケット写真
  - プレビューURL（ある場合のみ）
- [ ] 部分一致や大文字小文字の違いを許容して検索が行える。
- [ ] 検索結果が空の場合、「該当なし」のメッセージが適切に表示される。
- [ ] プレビューURLがない楽曲では、再生ボタンが非表示または無効化されている。

**Comment by kogoro06** [comment]
プレビューURLが仕様変更により、開発モードでは利用できなくなったため
spotifyに申請後許可が降り次第実装
