### ISSUE TITLE
感情をenumで選択できるようにする（indexへの動的表示も）

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#17]
## TODO
TODO

- [x] 1. Journal モデルに感情（喜怒哀楽と普通）の enum を作成
- [x] new ページで enum を用いて選択できるようにする
- [x]  index ページで感情を動的に表示
- [x] 感情に基づいて日記を絞り込む

## 要件

- [ ] Journalモデルに感情（喜怒哀楽と普通）のenumを作成
- [ ] newページでenumを用いてせんたくできるようにすること
- [ ] indexページで動的に表示できること
- [ ] enumで選んだ感情に基づいて、日記を絞り込めること
