### ISSUE TITLE
日記一覧(Journals/index)ページの作成

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#19]
## TODO
- [ ] ページの最上部に`User's Journal`という形でUser名を動的に表示する
- [ ] 各Journalの内容は上から日記のタイトル、感情、Spotifyで取得した楽曲情報（楽曲名、アーティスト名）とする（全て動的に表示されるようにする）
 
## 要件
- [ ] ページの最上部に`User's Journal`という形でUser名を動的に表示する
- [ ] 各Journalの内容は上から日記のタイトル、感情、Spotifyでしゅとくした楽曲情報（楽曲名、アーティスト名）とする（全て動的に表示されるようにする）
