### ISSUE TITLE
deviseのセットアップ

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#8]
## TODO

 - [x] Gemfile に devise を追加し、`bundle install` 実行
 - [x] `rails generate devise:install` 実行し、初期設定
- [x]  `rails g devise User`でuserモデルとマイグレーションを作成
- [x] `gem 'devise-i18n'`をGemFileに記載
- [x]  `bundle install`後にターミナルで`rails g devise:i18n:locale ja
`を打ち込む

## 要件
- Devise gemがインストールされ、基本的な設定が完了していること。
- サインアップページやログインページが表示できるようになっていること
- `devise.views.ja.yml`ファイルを作成している

## 参考資料
[deviseを日本語化する](https://qiita.com/you8/items/921e0dd1210eb0d158df#gem%E3%82%92%E5%B0%8E%E5%85%A5)
