### ISSUE TITLE
devise 新規登録機能

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/MySongJorunal#9]
## TODO: 

- [ ] `rails g devise:views`で作成されたビューを作成する。

- [ ] `app/views/devise/registrations/new.html.erb`に`form_for`内に`name`フィールドを追加する。

- [ ] `ApplicationController`に`configure_permitted_parameters`メソッドを定義し、`name`をサインアップ時のパラメータに追加。

- [ ] ユーザー名とプロフィール画像が正常に保存されることを確認する。

## **要件: **

- `users`テーブルに`name`と`avatar`カラムが追加されていること。
- サインアップページに`name`用のフォームが追加されていること。
- deviseを利用してサインアップが出来ること。
